# Generated by Django 4.2.4 on 2023-08-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('photo_url', models.ImageField(default='null', upload_to='users_profile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ini', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('company', models.CharField(max_length=100)),
                ('resume', models.CharField(max_length=2000)),
                ('skill', models.CharField(max_length=1000)),
                ('results', models.CharField(max_length=500)),
            ],
        ),
    ]
