# Generated by Django 4.2.4 on 2023-08-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_school_studies_alter_workexperience_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('by', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
